/*MUESTRA EL CODIGO NOMBRE Y DIRECCION DE LOS CLIENTES QUE NO SON DEL AREA TELEFONICA 636*/
USE empresa;
SELECT CLIENT_COD AS CODIGO, Nom as NOMBRE, Adreca as DIRECCION
FROM CLIENT
	WHERE AREA != 636;